package com.example.autoservice.service;

import com.example.autoservice.dto.ActivateLicenseRequest;
import com.example.autoservice.dto.CreateLicenseRequest;
import com.example.autoservice.dto.ExtendLicenseRequest;
import com.example.autoservice.dto.Ticket;
import com.example.autoservice.dto.TicketResponse;
import com.example.autoservice.model.Device;
import com.example.autoservice.model.DeviceLicense;
import com.example.autoservice.model.License;
import com.example.autoservice.model.LicenseHistory;
import com.example.autoservice.model.LicenseType;
import com.example.autoservice.model.Product;
import com.example.autoservice.model.User;
import com.example.autoservice.repository.DeviceLicenseRepository;
import com.example.autoservice.repository.DeviceRepository;
import com.example.autoservice.repository.LicenseHistoryRepository;
import com.example.autoservice.repository.LicenseRepository;
import com.example.autoservice.repository.LicenseTypeRepository;
import com.example.autoservice.repository.ProductRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.UUID;

@Service
public class LicenseService {
    private final LicenseRepository licenseRepo;
    private final DeviceRepository deviceRepo;
    private final DeviceLicenseRepository devLicRepo;
    private final ProductRepository productRepo;
    private final LicenseTypeRepository typeRepo;
    private final LicenseHistoryRepository historyRepo;
    private final SigningService signingService;

    public LicenseService(LicenseRepository lr,
                          DeviceRepository dr,
                          DeviceLicenseRepository dlr,
                          ProductRepository pr,
                          LicenseTypeRepository tr,
                          LicenseHistoryRepository hr,
                          SigningService signingService) {
        this.licenseRepo = lr;
        this.deviceRepo = dr;
        this.devLicRepo = dlr;
        this.productRepo = pr;
        this.typeRepo = tr;
        this.historyRepo = hr;
        this.signingService = signingService;
    }

    private void recordHistory(License license, User user, String status, String description) {
        LicenseHistory history = new LicenseHistory();
        history.setLicense(license);
        history.setUser(user);
        history.setStatus(status);
        history.setChange_date(Instant.now());
        history.setDescription(description);
        historyRepo.save(history);
    }

    @Transactional
    public License createLicense(CreateLicenseRequest request, User creator) {
        Product product = productRepo.findById(request.productId).orElseThrow();
        LicenseType type = typeRepo.findById(request.licenseTypeId).orElseThrow();

        License license = new License();
        license.setCode(UUID.randomUUID().toString());
        license.setUser(null);
        license.setProduct(product);
        license.setType(type);
        license.setBlocked(false);
        license.setDevice_count(0);

        License saved = licenseRepo.save(license);
        recordHistory(saved, creator, "CREATED", "License generated by admin");
        return saved;
    }

    @Transactional
    public TicketResponse activateLicense(ActivateLicenseRequest request, User user) {
        License license = licenseRepo.findLockedByCode(request.licenseCode)
                .orElseThrow(() -> new RuntimeException("License not found"));

        if (license.isBlocked()) {
            throw new RuntimeException("License is blocked");
        }

        if (license.getUser() == null) {
            license.setUser(user);
        } else if (!license.getUser().getId().equals(user.getId())) {
            throw new RuntimeException("This license belongs to another user");
        }

        Device device = deviceRepo.findByMacAddress(request.deviceMac).orElseGet(() -> {
            Device d = new Device();
            d.setMacAddress(request.deviceMac);
            d.setName(request.deviceName);
            d.setUser(user);
            return deviceRepo.save(d);
        });

        if (devLicRepo.existsByLicenseAndDevice(license, device)) {
            return buildResponse(license, device.getId());
        }

        if (license.getDevice_count() >= 2) {
            throw new RuntimeException("Device limit reached (max 2 devices)");
        }

        DeviceLicense dl = new DeviceLicense();
        dl.setLicense(license);
        dl.setDevice(device);
        dl.setActivation_date(Instant.now());
        devLicRepo.save(dl);

        license.setDevice_count(license.getDevice_count() + 1);

        if (license.getFirst_activation_date() == null) {
            license.setFirst_activation_date(Instant.now());
            license.setEnding_date(
                    Instant.now().plus(license.getType().getDefault_duration_in_days(), ChronoUnit.DAYS)
            );
        }

        licenseRepo.save(license);
        recordHistory(license, user, "ACTIVATED", "Activated on device: " + request.deviceMac);

        return buildResponse(license, device.getId());
    }

    @Transactional(readOnly = true)
    public TicketResponse verifyLicense(String mac, String code) {
        License license = licenseRepo.findByCode(code)
                .orElseThrow(() -> new RuntimeException("License not found"));

        Device device = deviceRepo.findByMacAddress(mac)
                .orElseThrow(() -> new RuntimeException("Device not found"));

        if (!devLicRepo.existsByLicenseAndDevice(license, device)) {
            throw new RuntimeException("Not activated");
        }

        if (license.isBlocked()) {
            throw new RuntimeException("License blocked");
        }

        if (license.getEnding_date().isBefore(Instant.now())) {
            throw new RuntimeException("Expired");
        }

        return buildResponse(license, device.getId());
    }

    @Transactional
    public TicketResponse extendLicense(ExtendLicenseRequest request, User user) {
        License license = licenseRepo.findLockedByCode(request.licenseCode)
                .orElseThrow(() -> new RuntimeException("License not found"));

        if (license.getUser() != null && !license.getUser().getId().equals(user.getId())) {
            throw new RuntimeException("Access denied");
        }

        Instant now = Instant.now();
        long daysRemaining = ChronoUnit.DAYS.between(now, license.getEnding_date());

        if (license.getEnding_date().isAfter(now) && daysRemaining > 7) {
            throw new RuntimeException("Extension allowed only when 7 or fewer days remain");
        }

        license.setEnding_date(
                license.getEnding_date().plus(license.getType().getDefault_duration_in_days(), ChronoUnit.DAYS)
        );
        licenseRepo.save(license);
        recordHistory(license, user, "RENEWED", "License extended");

        return buildResponse(license, null);
    }

    private TicketResponse buildResponse(License license, UUID deviceId) {
        Ticket ticket = new Ticket();
        ticket.serverDate = Instant.now();
        ticket.ticketLifetime = 3600;
        ticket.activationDate = license.getFirst_activation_date();
        ticket.expirationDate = license.getEnding_date();
        ticket.userId = license.getUser() != null ? license.getUser().getId() : null;
        ticket.deviceId = deviceId;
        ticket.blocked = license.isBlocked();

        TicketResponse response = new TicketResponse();
        response.ticket = ticket;
        response.signature = signingService.sign(ticket);
        return response;
    }
}